spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: member-module
          uri: lb://member-module
          predicates:
            - Path=/api/members/**, /api/auth/**
        - id: board-module
          uri: lb://board-module
          predicates:
            - Path=/api/boards/**

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG